import { Injectable } from '@angular/core';
import { Curso } from '../model/curso';

@Injectable({
  providedIn: 'root',
})
export class DatosService {
  private cursos: Curso[] = [
    {
      id: 1,
      familia: 'Informatica',
      nivel: 1,
      nombre: 'Desarrollo Aplicaciones Multiplataforma',
      asignaturas: [
        {
          id: 1,
          curso: '1',
          nombre: 'Programacion multimedia',
          siglas: 'PMDM',
          horas: 6,
          profesor: 'Borja',
          conocimientos: ['Kotlin', 'XML'],
        },
        {
          id: 2,
          curso: '1',
          nombre: 'Desarrollo interfaces',
          siglas: 'DI',
          horas: 6,
          profesor: 'Borja',
          conocimientos: ['Java', 'Javascript'],
        },
        {
          id: 3,
          curso: '2',
          nombre: 'Bases de Datos',
          siglas: 'BD',
          horas: 5,
          profesor: 'Ana',
          conocimientos: ['SQL', 'NoSQL'],
        },
        {
          id: 4,
          curso: '2',
          nombre: 'Redes y Comunicaciones',
          siglas: 'RC',
          horas: 4,
          profesor: 'Carlos',
          conocimientos: ['TCP/IP', 'DNS'],
        },
        {
          id: 5,
          curso: '1',
          nombre: 'Ciberseguridad Básica',
          siglas: 'CB',
          horas: 3,
          profesor: 'David',
          conocimientos: ['Seguridad', 'Redes'],
        },
        {
          id: 6,
          curso: '2',
          nombre: 'Inteligencia Artificial Avanzada',
          siglas: 'IAA',
          horas: 7,
          profesor: 'Elena',
          conocimientos: ['Python', 'Machine Learning'],
        },
        {
          id: 7,
          curso: '1',
          nombre: 'Desarrollo Web con JavaScript',
          siglas: 'DWJS',
          horas: 5,
          profesor: 'Fernando',
          conocimientos: ['JavaScript', 'HTML', 'CSS'],
        },
        {
          id: 8,
          curso: '2',
          nombre: 'Administración de Sistemas Linux',
          siglas: 'ASL',
          horas: 4,
          profesor: 'Gabriel',
          conocimientos: ['Linux', 'Bash'],
        },
        {
          id: 9,
          curso: '1',
          nombre: 'Ingeniería del Software',
          siglas: 'ISW',
          horas: 6,
          profesor: 'Hector',
          conocimientos: ['UML', 'Patrones de Diseño'],
        },
        {
          id: 10,
          curso: '2',
          nombre: 'Robótica Avanzada',
          siglas: 'RA',
          horas: 8,
          profesor: 'Isabel',
          conocimientos: ['Robótica', 'Electrónica'],
        },
      ],
    },
    {
      id: 2,
      familia: 'Informatica',
      nivel: 1,
      nombre: 'Sistemas Informáticos',
      asignaturas: [
        {
          id: 1,
          curso: '1',
          nombre: 'Programacion multimedia',
          siglas: 'PMDM',
          horas: 6,
          profesor: 'Borja',
          conocimientos: ['Kotlin', 'XML'],
        },
        {
          id: 2,
          curso: '1',
          nombre: 'Desarrollo interfaces',
          siglas: 'DI',
          horas: 6,
          profesor: 'Borja',
          conocimientos: ['Java', 'Javascript'],
        },
        {
          id: 3,
          curso: '2',
          nombre: 'Bases de Datos',
          siglas: 'BD',
          horas: 5,
          profesor: 'Ana',
          conocimientos: ['SQL', 'NoSQL'],
        },
        {
          id: 4,
          curso: '2',
          nombre: 'Redes y Comunicaciones',
          siglas: 'RC',
          horas: 4,
          profesor: 'Carlos',
          conocimientos: ['TCP/IP', 'DNS'],
        },
        {
          id: 5,
          curso: '1',
          nombre: 'Ciberseguridad Básica',
          siglas: 'CB',
          horas: 3,
          profesor: 'David',
          conocimientos: ['Seguridad', 'Redes'],
        },
        {
          id: 6,
          curso: '2',
          nombre: 'Inteligencia Artificial Avanzada',
          siglas: 'IAA',
          horas: 7,
          profesor: 'Elena',
          conocimientos: ['Python', 'Machine Learning'],
        },
        {
          id: 7,
          curso: '1',
          nombre: 'Desarrollo Web con JavaScript',
          siglas: 'DWJS',
          horas: 5,
          profesor: 'Fernando',
          conocimientos: ['JavaScript', 'HTML', 'CSS'],
        },
        {
          id: 8,
          curso: '2',
          nombre: 'Administración de Sistemas Linux',
          siglas: 'ASL',
          horas: 4,
          profesor: 'Gabriel',
          conocimientos: ['Linux', 'Bash'],
        },
        {
          id: 9,
          curso: '1',
          nombre: 'Ingeniería del Software',
          siglas: 'ISW',
          horas: 6,
          profesor: 'Hector',
          conocimientos: ['UML', 'Patrones de Diseño'],
        },
        {
          id: 10,
          curso: '2',
          nombre: 'Robótica Avanzada',
          siglas: 'RA',
          horas: 8,
          profesor: 'Isabel',
          conocimientos: ['Robótica', 'Electrónica'],
        },
      ],
    },
    {
      id: 3,
      familia: 'Informatica',
      nivel: 1,
      nombre: 'Redes y Comunicaciones',
      asignaturas: [
        {
          id: 1,
          curso: '1',
          nombre: 'Programacion multimedia',
          siglas: 'PMDM',
          horas: 6,
          profesor: 'Borja',
          conocimientos: ['Kotlin', 'XML'],
        },
        {
          id: 2,
          curso: '1',
          nombre: 'Desarrollo interfaces',
          siglas: 'DI',
          horas: 6,
          profesor: 'Borja',
          conocimientos: ['Java', 'Javascript'],
        },
        {
          id: 3,
          curso: '2',
          nombre: 'Bases de Datos',
          siglas: 'BD',
          horas: 5,
          profesor: 'Ana',
          conocimientos: ['SQL', 'NoSQL'],
        },
        {
          id: 4,
          curso: '2',
          nombre: 'Redes y Comunicaciones',
          siglas: 'RC',
          horas: 4,
          profesor: 'Carlos',
          conocimientos: ['TCP/IP', 'DNS'],
        },
        {
          id: 5,
          curso: '1',
          nombre: 'Ciberseguridad Básica',
          siglas: 'CB',
          horas: 3,
          profesor: 'David',
          conocimientos: ['Seguridad', 'Redes'],
        },
        {
          id: 6,
          curso: '2',
          nombre: 'Inteligencia Artificial Avanzada',
          siglas: 'IAA',
          horas: 7,
          profesor: 'Elena',
          conocimientos: ['Python', 'Machine Learning'],
        },
        {
          id: 7,
          curso: '1',
          nombre: 'Desarrollo Web con JavaScript',
          siglas: 'DWJS',
          horas: 5,
          profesor: 'Fernando',
          conocimientos: ['JavaScript', 'HTML', 'CSS'],
        },
        {
          id: 8,
          curso: '2',
          nombre: 'Administración de Sistemas Linux',
          siglas: 'ASL',
          horas: 4,
          profesor: 'Gabriel',
          conocimientos: ['JavaScript', 'HTML', 'CSS'],
        },
      ],
    },
    {
      id: 11,
      familia: 'Informatica',
      nivel: 1,
      nombre: 'Big Data',
      asignaturas: [
        {
          id: 1,
          curso: '1',
          nombre: 'Programacion multimedia',
          siglas: 'PMDM',
          horas: 6,
          profesor: 'Borja',
          conocimientos: ['Kotlin', 'XML'],
        },
        {
          id: 2,
          curso: '1',
          nombre: 'Desarrollo interfaces',
          siglas: 'DI',
          horas: 6,
          profesor: 'Borja',
          conocimientos: ['Java', 'Javascript'],
        },
        {
          id: 3,
          curso: '2',
          nombre: 'Bases de Datos',
          siglas: 'BD',
          horas: 5,
          profesor: 'Ana',
          conocimientos: ['SQL', 'NoSQL'],
        },
        {
          id: 4,
          curso: '2',
          nombre: 'Redes y Comunicaciones',
          siglas: 'RC',
          horas: 4,
          profesor: 'Carlos',
          conocimientos: ['TCP/IP', 'DNS'],
        },
        {
          id: 5,
          curso: '1',
          nombre: 'Ciberseguridad Básica',
          siglas: 'CB',
          horas: 3,
          profesor: 'David',
          conocimientos: ['Seguridad', 'Redes'],
        },
        {
          id: 6,
          curso: '2',
          nombre: 'Inteligencia Artificial Avanzada',
          siglas: 'IAA',
          horas: 7,
          profesor: 'Elena',
          conocimientos: ['Python', 'Machine Learning'],
        },
        {
          id: 7,
          curso: '1',
          nombre: 'Desarrollo Web con JavaScript',
          siglas: 'DWJS',
          horas: 5,
          profesor: 'Fernando',
          conocimientos: ['JavaScript', 'HTML', 'CSS'],
        },
        {
          id: 8,
          curso: '2',
          nombre: 'Administración de Sistemas Linux',
          siglas: 'ASL',
          horas: 4,
          profesor: 'Gabriel',
          conocimientos: ['Linux', 'Bash'],
        },
        {
          id: 9,
          curso: '1',
          nombre: 'Ingeniería del Software',
          siglas: 'ISW',
          horas: 6,
          profesor: 'Hector',
          conocimientos: ['UML', 'Patrones de Diseño'],
        },
        {
          id: 10,
          curso: '2',
          nombre: 'Robótica Avanzada',
          siglas: 'RA',
          horas: 8,
          profesor: 'Isabel',
          conocimientos: ['Robótica', 'Electrónica'],
        },
      ],
    },
    {
      id: 12,
      familia: 'Informatica',
      nivel: 1,
      nombre: 'Desarrollo Web',
      asignaturas: [
        {
          id: 1,
          curso: '1',
          nombre: 'Programacion multimedia',
          siglas: 'PMDM',
          horas: 6,
          profesor: 'Borja',
          conocimientos: ['Kotlin', 'XML'],
        },
        {
          id: 2,
          curso: '1',
          nombre: 'Desarrollo interfaces',
          siglas: 'DI',
          horas: 6,
          profesor: 'Borja',
          conocimientos: ['Java', 'Javascript'],
        },
        {
          id: 3,
          curso: '2',
          nombre: 'Bases de Datos',
          siglas: 'BD',
          horas: 5,
          profesor: 'Ana',
          conocimientos: ['SQL', 'NoSQL'],
        },
        {
          id: 4,
          curso: '2',
          nombre: 'Redes y Comunicaciones',
          siglas: 'RC',
          horas: 4,
          profesor: 'Carlos',
          conocimientos: ['TCP/IP', 'DNS'],
        },
        {
          id: 5,
          curso: '1',
          nombre: 'Ciberseguridad Básica',
          siglas: 'CB',
          horas: 3,
          profesor: 'David',
          conocimientos: ['Seguridad', 'Redes'],
        },
        {
          id: 6,
          curso: '2',
          nombre: 'Inteligencia Artificial Avanzada',
          siglas: 'IAA',
          horas: 7,
          profesor: 'Elena',
          conocimientos: ['Python', 'Machine Learning'],
        },
        {
          id: 7,
          curso: '1',
          nombre: 'Desarrollo Web con JavaScript',
          siglas: 'DWJS',
          horas: 5,
          profesor: 'Fernando',
          conocimientos: ['JavaScript', 'HTML', 'CSS'],
        },
        {
          id: 8,
          curso: '2',
          nombre: 'Administración de Sistemas Linux',
          siglas: 'ASL',
          horas: 4,
          profesor: 'Gabriel',
          conocimientos: ['Linux', 'Bash'],
        },
        {
          id: 9,
          curso: '1',
          nombre: 'Ingeniería del Software',
          siglas: 'ISW',
          horas: 6,
          profesor: 'Hector',
          conocimientos: ['UML', 'Patrones de Diseño'],
        },
        {
          id: 10,
          curso: '2',
          nombre: 'Robótica Avanzada',
          siglas: 'RA',
          horas: 8,
          profesor: 'Isabel',
          conocimientos: ['Robótica', 'Electrónica'],
        },
      ],
    },
  ];

  constructor() {}

  // todas las funcionalidades que me interesa gestionar con los datos

  getAllCursosByFamilia(familia: string): Curso[] {
    return this.cursos.filter((item) => item.familia == familia);
  }

  getAllCursos(): Curso[] {
    return this.cursos;
  }


  // getAsgnaturaById(id) -> asginaturas
  // getCursoById(id) -> cursos
}
